if metro >= 0.51, require from metro-react-native-babel-transformer
bamlab/react-native-graphql-transformer pull request #7
Opened 2019-03-10 12:50 UTC by smeevil

This solves: https://github.com/bamlab/react-native-graphql-transformer/issues/6

2019-04-18 18:52 UTC, sterlingwes commented
@tpucci can we have this ❓ 🙏

2019-04-19 06:26 UTC, tpucci requested changes
I think we should use semver to compare versions. Parsing as a float may be dangerous if metro ever decide to use the semver standard someday.

2019-04-19 06:26 UTC, tpucci commented on index.js
> +const metroVersion = parseFloat(require('metro/package.json').version);
Parsing the version as a float seems a little hacky to me.
Could you use the same syntax as `reactNativeMinorVersion` ?

Like:
```js
const metroVersionString = require('metro/package.json').version;

const metroMinorVersion = semver(metroVersionString).minor;
```

2019-04-19 06:26 UTC, tpucci commented on index.js
> +if (metroVersion >= 0.51) {
Then, this would become: 

```js
if (metroMinorVersion >= 51) {
...
}
```

2019-06-17 09:16 UTC, duyleekun commented
Anyone?

2019-07-08 13:44 UTC, merged